Document: patator
Title: Debian patator Manual
Author: <insert document author here>
Abstract: This manual describes what patator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/patator/patator.sgml.gz

Format: postscript
Files: /usr/share/doc/patator/patator.ps.gz

Format: text
Files: /usr/share/doc/patator/patator.text.gz

Format: HTML
Index: /usr/share/doc/patator/html/index.html
Files: /usr/share/doc/patator/html/*.html
